# R Markdown

在本次研讨会中，我将向您展示如何使用 R Markdown 生成 `.html` 格式的报告。 使用 R Markdown 编写的报告允许您将编写的叙述与 R 代码块以及与这些代码块相关的输出全部合并到一个knitted文档中。 本单元的作业需要使用 R Markdown 生成。

## 概述 {-}

在这个研讨会中，我们将简要介绍如何使用R Markdown生成包含叙述、代码和代码输出的报告。

在下面的视频中，我将简要介绍如何将您编写的R脚本转换为R Markdown文档，您可以将其“编织”并与他人共享。

<center>
<iframe src="【在此输入视频地址RMarkdown】" allowfullscreen="allowfullscreen" width="100%" height="500" scrolling="no" frameborder="0" sandbox="allow-top-navigation allow-same-origin allow-forms allow-scripts"> </iframe> 
</center>

有很多资源可帮助您探索 R Markdown 的各种可能性。一个很好的起点是 Yihui Xie、J. J. Allaire 和 Garrett Grolemund 的《R Markdown: The Definitive Guide》。只需点击[这个链接](https://bookdown.org/yihui/rmarkdown/)即可进入该书的在线版本。

您可能还对 Yihui Xie、Christophe Dervieux 和 Emily Riederer 的“R Markdown Cookbook”感兴趣。再次，只需点击[这个链接](https://bookdown.org/yihui/rmarkdown-cookbook/)即可进入该书的在线版本。

## 作业 {-}

拿出你已经写好的脚本之一 - 也许是你开发的可视化脚本之一 - 并使用它创建一个 R Markdown 文档。将你的脚本代码添加到一个新的 R Markdown 文档中，以有意义的小代码块的形式（每个代码块可能只有几行代码） - 你可能有一个代码块来加载你的库，一个代码块来读取你的数据，另一个代码块用于整理你的数据，然后为你编写的每个可视化部分分别创建代码块。在每个小代码块之前，添加一些解释以下代码块的叙述。调整每个代码块开头的消息和警告参数，以便警告和消息不会显示在最终生成的 R Markdown `.html `文件中。

记住，当你编写一个 R Markdown 文档时，它是在它自己的 R 会话中工作的，因此无法访问你编写 R Markdown 文档所在的主要 R 会话中的任何内容。这意味着你的 R Markdown 必须在文档内部加载所需的库并读取数据。

这个单元中的所有内容都是用R Markdown编写的 - 所以如果你想看看我是如何做到的，你可以点击[这个](https://github.com/azanghai/R4Starter)链接，然后查看相关GitHub仓库上脚本文件夹中的.Rmd文件。

## 帮助我们改进本节课程 {.unnumbered}

*此处应插入文本和反馈二维码或问卷链接*
